[package]
name = "stripe-by-diwazz"
version = "0.1.0"
description = "Stripe card checker API"

[dependencies]
"sharrattj/python" = "3.12.6"

[fs]
"/app" = "."

[[command]]
name = "run"
module = "sharrattj/python:python"
runner = "wasi"

[command.runner.wasi]
main-args = [
    "-m",
    "gunicorn",
    "--bind=0.0.0.0:8000",
    "--workers=1",
    "--timeout=120",
    "--chdir=/app",
    "app:app"
]
env = ["PYTHONUNBUFFERED=1", "PYTHONPATH=/app"]
