[package]
name = "stripe-by-diwazz"
version = "0.1.0"
description = "Stripe card checker API"

[dependencies]
"python/python" = "=3.12.7"

[[module]]
name = "stripe-by-diwazz"
source = "start.py"
abi = "wasi"

[fs]
"/" = "."

[[command]]
name = "script"
module = "stripe-by-diwazz"
runner = "https://webc.org/runner/python/python@3.12"

[command.annotations.wasi]
env = ["PORT=8000"]
